#!/usr/bin/ansible-playbook

- hosts: all

  vars:
    default_ost_images_repo_url: 'https://templates.ovirt.org/yum/'
    default_ost_images_rpms:
      - ost-images-el8stream-engine-installed
      - ost-images-el8stream-host-installed
      - ost-images-node-base

  tasks:
    - name: enable nested virtualization on intel
      lineinfile:
        path: /etc/modprobe.d/kvm.conf
        create: yes
        line: options kvm_intel nested=1
      become: true
      notify: reboot
      when: ansible_facts['processor'][1] == 'GenuineIntel'

    - name: enable nested virtualization on amd
      lineinfile:
        path: /etc/modprobe.d/kvm.conf
        create: yes
        line: options kvm_amd nested=1
      become: true
      notify: reboot
      when: ansible_facts['processor'][1] == 'AuthenticAMD'

    - name: set accept_ra on ipv6
      lineinfile:
        path: /etc/sysctl.d/90-ost-ipv6-ra.conf
        create: yes
        line: net.ipv6.conf.all.accept_ra=2
      become: true

    - name: set up ost-images repo
      yum_repository:
        name: ost-images
        description: ost-images
        baseurl: "{{ ost_images_repo_url | default(default_ost_images_repo_url) }}"
        gpgcheck: no
      become: true

    - name: install packages and cleanup epel if necessary

      block:
        - name: install epel
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            disable_gpg_check: yes
          become: true
          register: epel

        - name: install required packages for OST
          dnf:
            name:
              - ansible
            state: present
          dnf:
            name:
              - gcc
              - git
              - libcurl-devel
              - libvirt
              - libxml2-devel
              - openssl
              - openssl-devel
              - podman
              - python39
              - python39-devel
              - qemu-kvm
            state: latest
          become: true

        - name: install required packages for building ost-images
          dnf:
            name:
              - autoconf
              - automake
              - createrepo
              - jq
              - make
              - rpm-build
              - virt-install
            state: latest
          become: true

      always:
        - name: remove epel if it was added
          dnf:
            name: epel-release-8
            state: absent
          when: epel.changed
          become: true

    - name: install ost images
      dnf:
        name: "{{ ost_images_rpms | default(default_ost_images_rpms) }}"
      become: true

    - name: add user to relevant groups
      user:
        name: "{{ ansible_facts['user_id'] }}"
        groups:
          - qemu
      become: true

    - name: add qemu to the user group
      user:
        name: qemu
        groups:
          - "{{ ansible_facts['user_id'] }}"
      become: true

    - name: allow user to manage libvirt
      template:
        dest: /etc/polkit-1/localauthority/50-local.d/ost-libvirt.pkla
        group: root
        mode: '0644'
        owner: root
        src: ost-libvirt.pkla.in
      become: true

    - name: restart polkit
      systemd:
        name: polkit
        state: restarted
      become: true

    - name: set user home directory permissions
      file:
        path: "{{ ansible_facts['user_dir'] }}"
        mode: 0751
      become: true

    - name: allow virtlogd to write console logs
      selinux_permissive:
        name: virtlogd_t
        permissive: true
      become: true

  handlers:
    - name: reboot
      debug:
        msg: Please reboot to apply all the changes.
