---
- name: Create network 10
  os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: net10
  register: net10

- name: Create net10_subnet 1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: present
    network_name: "{{ net10.id }}"
    name: net10_subnet1
    ip_version: 4
    cidr: 10.10.0.0/24
    gateway_ip: 10.10.0.1
    enable_dhcp: yes
  register: net10_subnet1

- name: Create port net10_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: present
    name: net10_port1
    network: net10
    fixed_ips:
      - ip_address: 10.10.0.11

- name: Create network 11
  os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: net11
  register: net11

- name: Create net11_subnet 1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: present
    network_name: "{{ net11.id }}"
    name: net11_subnet1
    ip_version: 4
    cidr: 10.11.0.0/24
    gateway_ip: 10.11.0.1
    enable_dhcp: yes
  register: net11_subnet1

- name: Create port net11_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: present
    name: net11_port1
    network: net11
    fixed_ips:
      - ip_address: 10.11.0.11

- name: Create network 12
  os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: net12
  register: net12

- name: Create net12_subnet 1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: present
    network_name: "{{ net12.id }}"
    name: net12_subnet1
    ip_version: 4
    cidr: 10.12.0.0/24
    gateway_ip: 10.12.0.1
    enable_dhcp: yes
  register: net12_subnet1

- name: Create port net12_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: present
    name: net12_port1
    network: net12
    fixed_ips:
      - ip_address: 10.12.0.11

- name: Create router0
  os_router:
    cloud: "{{ cloud_name }}"
    state: present
    name: router0
    interfaces:
        - net10_subnet1
        - net11_subnet1
        - net12_subnet1
