---

# Remove the router before removing the subnet to remove the router interfaces
- name: Remove router0
  os_router:
    cloud: "{{ cloud_name }}"
    state: absent
    name: router0

- name: Remove simple_net_subnet
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: absent
    name: simple_net_subnet

- name: Remove port simple_net_port2
  os_port:
    cloud: "{{ cloud_name }}"
    state: absent
    name: simple_net_port2

- name: Remove simple network
  os_network:
    cloud: "{{ cloud_name }}"
    state: absent
    name: simple_net
