---
- name: Remove simple_net_subnet
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: absent
    name: simple_net_subnet

- name: Remove simple network
  os_network:
    cloud: "{{ cloud_name }}"
    state: absent
    name: simple_net
