---
- name: Ensure that hostname of engine is resolved
  hosts: localhost

  tasks:
    - lineinfile:
        dest: /etc/hosts
        line: "{{ engine_ip }} {{ engine_fqdn | default('engine') }}"
        state: present
      when: engine_ip is defined